title: Subhrajit Prusty
url: "https://subhrajitprusty.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: ./media/favicon.png

tracking_id: #

footer: no
footer_url: "https://github.com/SubhrajitPrusty"
footer_text: Subhrajit Prusty

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "public/cv.pdf"
 - name: Youtube
   link: /youtube
 - name: "Blog"
   link: /blogs


js: app.js
json: package.json
